FORMAT: 1A
HOST: http://api.gridticker.com/v1

# GridTicker
GridTicker API is an *IoT Platform* service collects ticks from any thing connected with the GridTicker.

# Group Tickers
Ticker related resources of the **GridTicker API**

## Ticker Collection [/tickers]
### List all Tickers [GET]
+ Response 200 (application/json)

        [{
          "id": 1, "name": "Raspberry Pi"
        }, {
          "id": 2, "name": "Arduino"
        }]

### Create a Ticker [POST]
+ Request (application/json)

        { "name": "Raspberry Pi in Qemu" }

+ Response 201 (application/json)

        { "id": 3, "name": "Raspberry Pi in Qemu" }

## Ticker [/tickers/{id}]
A single Ticker object with all its details

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Ticker to perform action with. Has example value.

### Retrieve a Ticker [GET]
+ Response 200 (application/json)

    + Header

            X-My-Header: The Value

    + Body

            { "id": 2, "name": "Arduino" }

### Remove a Ticker [DELETE]
+ Response 204

# Group Ticks
Tick related resources of the **GridTicker API**

## Tick Collection [/ticks]
### List all Ticks [GET]
+ Response 200 (application/json)

        [{
          "id": 1, "name": "Temperature", "value": "35.5"
        }, {
          "id": 2, "name": "Temperature", "value": "28.7"
        }]

### Create a Ticker [POST]
+ Request (application/json)

        { "name": "Temperature", "value": "45.2" }

+ Response 201 (application/json)

        { "id": 3, "name": "Temperature", "value": "45.2"  }

## Tick [/ticks/{id}]
A single Tick object with all its details

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Tick to perform action with. Has example value.

### Retrieve a Tick [GET]
+ Response 200 (application/json)

    + Header

            X-My-Header: The Value

    + Body

            { "id": 2, "name": "Temperature", "value": "28.7" }

### Remove a Tick [DELETE]
+ Response 204
